// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqwnyjatrflzlueqfxbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxd255amF0cmZsemx1ZXFmeGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTk5ODksImV4cCI6MjA2NDYzNTk4OX0.FYrSm3WTl2ziKwH1_CURtARvtab6C7KvZmiL9ZRWaNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);